# monitors
$monitorA=eDP-1
$monitorB=HDMI-A-1

# modifiers
$mainMod = SUPER
$altControl = Alt_CTRL
$modA = Alt_CTRL
$modB = Alt_SHIFT
$modC = SUPER


# colours
$activeBorder = 595959FF
$activeBorder = 000000FF
$border = 000000FF
$activeShadow = 0092ff99


# wallpaper
$wallpaper = street.jpg

